Fail deploy script if DEPLOY_ENV not set

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -6,6 +6,11 @@ if [[ -n $1 ]]; then
   DEPLOY_ENV=$1
 fi
 
+if [[ -z $DEPLOY_ENV ]]; then
+  echo "DEPLOY_ENV is required (can be given as first arg to script)"
+  exit 1
+fi
+
 if [[ "${BUILDKITE_PULL_REQUEST}" != "false" ]]; then
   echo "Not deploying because this is a pull request"
   exit 0
